### PR TITLE
Add Logo to RugRugToken on Mist Swap

### PR DESCRIPTION
**Pull request by GodfatherForTokens**
This time I'm definitely sure I did it, image came up and everything.

### CODE REVIEW

**Comment by kasumi-1** [comment]
Hi! The casing on the word Logo is incorrect. It should be logo.png, not Logo.png.

**Comment by GodfatherForTokens** [comment]
It auto-capitlized when I renamed it, does it make it unusable?

**Comment by kasumi-1** [comment]
yes

**Comment by GodfatherForTokens** [comment]
Ok I went in and redid it

**Comment by GodfatherForTokens** [comment]
Just had to stop it from being auto capped. Hope this one works!

**Comment by kasumi-1** [comment]
you deleted most of the token contract folder name, so this wont work. please check the readme which has full walkthrough instructions https://github.com/mistswapdex/assets#to-add-logo

**Comment by GodfatherForTokens** [comment]
Sorry, I swear I am reading it and trying, I'm just somehow failing. First time working gethub using youtube tutorials.

**Comment by GodfatherForTokens** [comment]
I... don't even know how I did that... I see the problem, sorry.

**Comment by GodfatherForTokens** [comment]
Ok. It all matches now, no uppercase png, full ca, picture showed, under 100 kb, 256 by 256

**Comment by GodfatherForTokens** [comment]
Thanks for putting me in the right direction. I'm gonna pass out now.

**Pull request merged**
